CREATE TABLE MST_USER
(
	  ID VARCHAR2(50 BYTE) NOT NULL 
	, NAME NVARCHAR2(50) NOT NULL 
	, MAIL VARCHAR2(128 BYTE) 
	, NOTE NVARCHAR2(50) 
	, ADMIN NUMBER(1, 0) DEFAULT 0 NOT NULL 
	, INSERTDATE DATE NOT NULL 
	, UPDATEDATE DATE NOT NULL 
	, CONSTRAINT MST_USER_PK PRIMARY KEY 
	  (
	    ID 
	  )
	  ENABLE 
);

COMMENT ON COLUMN MST_USER.ID IS 'ID';
COMMENT ON COLUMN MST_USER.NAME IS '名称';
COMMENT ON COLUMN MST_USER.MAIL IS 'メール';
COMMENT ON COLUMN MST_USER.NOTE IS '備考';
COMMENT ON COLUMN MST_USER.ADMIN IS '管理者';
COMMENT ON COLUMN MST_USER.INSERTDATE IS '作成日';
COMMENT ON COLUMN MST_USER.UPDATEDATE IS '変更日';

