'------------------------------------------------------------------------------
' <auto-generated>
'     このコードはツールによって生成されました。
'     ランタイム バージョン:4.0.30319.42000
'
'     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
'     コードが再生成されるときに損失したりします。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports Moca.Db
Imports Moca.Db.Attr
Imports System.ComponentModel


''' <summary> 
''' UserRow Entity 
''' </summary> 
''' <remarks></remarks> 
''' <history> 
''' </history> 
Public Class UserRowOra
	Implements System.ComponentModel.INotifyPropertyChanged

#Region " Declare "
	Shared _def As IUserDefinition

	Private _id As String

	Private _name As String

	Private _mail As String

	Private _note As String

	Private _admin As Boolean

	Private _insertDate As Date

	Private _updateDate As Date
#End Region

#Region " Property "
	''' <summary> 
	''' Id (Id) Property. 
	''' </summary> 
	<Column("ID")>
	Public Property Id() As String
		Get
			Return Me._id
		End Get
		Set
			Me._id = Value
			OnPropertyChanged("Id")
		End Set
	End Property

	''' <summary> 
	''' Name (Name) Property. 
	''' </summary> 
	<Column("NAME")>
	Public Property Name() As String
		Get
			Return Me._name
		End Get
		Set
			Me._name = Value
			OnPropertyChanged("Name")
		End Set
	End Property

	''' <summary> 
	''' Mail (Mail) Property. 
	''' </summary> 
	<Column("MAIL")>
	Public Property Mail() As String
		Get
			Return Me._mail
		End Get
		Set
			Me._mail = Value
			OnPropertyChanged("Mail")
		End Set
	End Property


	''' <summary> 
	''' Note (Note) Property. 
	''' </summary> 
	<Column("NOTE")>
	Public Property Note() As String
		Get
			Return Me._note
		End Get
		Set
			Me._note = Value
			OnPropertyChanged("Note")
		End Set
	End Property

	''' <summary> 
	''' Admin (Admin) Property. 
	''' </summary> 
	<Column("ADMIN")>
	Public Property Admin() As Object
		Get
			Return Me._admin
		End Get
		Set
			Me._admin = Value
			OnPropertyChanged("Admin")
		End Set
	End Property


	''' <summary> 
	''' InsertDate (InsertDate) Property. 
	''' </summary> 
	<Column("INSERTDATE")>
	Public Property InsertDate() As Date
		Get
			Return Me._insertDate
		End Get
		Set
			Me._insertDate = Value
			OnPropertyChanged("InsertDate")
		End Set
	End Property


	''' <summary> 
	''' UpdateDate (UpdateDate) Property. 
	''' </summary> 
	<Column("UPDATEDATE")>
	Public Property UpdateDate() As Date
		Get
			Return Me._updateDate
		End Get
		Set
			Me._updateDate = Value
			OnPropertyChanged("UpdateDate")
		End Set
	End Property


#End Region

#Region " PropertyChanged "
	Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged

	Protected Overridable Sub OnPropertyChanged(ByVal name As String)
		RaiseEvent PropertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(name))
	End Sub
#End Region

End Class

#Region " Definition "
''' <summary> 
''' User Entity definition 
''' </summary> 
''' <remarks></remarks> 
''' <history> 
''' </history> 
<Table("MocaCore.Test.My.MySettings.Ora", "MSTUSER")>
Public Interface IUserDefinitionOra

	''' <summary> 
	''' Table (Table) Property. 
	''' </summary> 
	Property Table() As Moca.Db.DbInfoTable

	''' <summary> 
	''' Id (Id) Property. 
	''' </summary> 
	<Column("ID")>
	Property Id() As Moca.Db.DbInfoColumn

	''' <summary> 
	''' Name (Name) Property. 
	''' </summary> 
	<Column("NAME")>
	Property Name() As Moca.Db.DbInfoColumn

	''' <summary> 
	''' Mail (Mail) Property. 
	''' </summary> 
	<Column("MAIL")>
	Property Mail() As Moca.Db.DbInfoColumn

	''' <summary> 
	''' Note (Note) Property. 
	''' </summary> 
	<Column("NOTE")>
	Property Note() As Moca.Db.DbInfoColumn

	''' <summary> 
	''' Admin (Admin) Property. 
	''' </summary> 
	<Column("ADMIN")>
	Property Admin() As Moca.Db.DbInfoColumn

	''' <summary> 
	''' InsertDate (InsertDate) Property. 
	''' </summary> 
	<Column("INSERTDATE")>
	Property InsertDate() As Moca.Db.DbInfoColumn

	''' <summary> 
	''' UpdateDate (UpdateDate) Property. 
	''' </summary> 
	<Column("UPDATEDATE")>
	Property UpdateDate() As Moca.Db.DbInfoColumn
End Interface
#End Region
