'------------------------------------------------------------------------------
' <auto-generated>
'     このコードはツールによって生成されました。
'     ランタイム バージョン:4.0.30319.42000
'
'     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
'     コードが再生成されるときに損失したりします。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports Moca.Db
Imports Moca.Db.Attr
Imports System.ComponentModel
Imports System.Runtime.CompilerServices


''' <summary> 
''' MstUser Entity definition 
''' </summary> 
''' <remarks></remarks> 
''' <history> 
''' </history> 
<Table("MocaCore.Test.My.MySettings.MSSQL", "mstUser")>
Public Interface IMstUserTbInfo

    ''' <summary> 
    ''' Id (Id) Property. 
    ''' </summary> 
    <Column("Id")>
    Property Id() As Moca.Db.DbInfoColumn

    ''' <summary> 
    ''' Name (Name) Property. 
    ''' </summary> 
    <Column("Name")>
    Property Name() As Moca.Db.DbInfoColumn

    ''' <summary> 
    ''' Mail (Mail) Property. 
    ''' </summary> 
    <Column("Mail")>
    Property Mail() As Moca.Db.DbInfoColumn

    ''' <summary> 
    ''' Note (Note) Property. 
    ''' </summary> 
    <Column("Note")>
    Property Note() As Moca.Db.DbInfoColumn

    ''' <summary> 
    ''' Admin (Admin) Property. 
    ''' </summary> 
    <Column("Admin")>
    Property Admin() As Moca.Db.DbInfoColumn

    ''' <summary> 
    ''' InsertDate (InsertDate) Property. 
    ''' </summary> 
    <Column("InsertDate")>
    Property InsertDate() As Moca.Db.DbInfoColumn

    ''' <summary> 
    ''' UpdateDate (UpdateDate) Property. 
    ''' </summary> 
    <Column("UpdateDate")>
    Property UpdateDate() As Moca.Db.DbInfoColumn
End Interface
